services:

  _defaults:
    public: false
    autowire: true

  Ramsterhad\DeepDanbooruTagAssist\Application\:
    resource: '*'
    #exclude: '../{DependencyInjection,Entity,Tests,Kernel.php}'


  # Controller

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\AuthenticationController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\AuthenticationFormController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\LogoutController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\ApiUrlController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\FrontpageController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\PushTagsController:
    public: true


  # Factories

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Factory\PostFactory:
    public: true

#  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Factory\SplFileObjectFromUrlFactory:
#    public: true


  # Services

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Adapter\AdapterInterface:
    class: Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Adapter\CurlAdapter
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\AuthenticationService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\EndpointUrlService:
    public: true

#  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\DanbooruBridgeService:
#    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\PushTagsService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\RequestPostService:
    public: true
