services:

  _defaults:
    public: false
    autowire: true

  Ramsterhad\DeepDanbooruTagAssist\Framework\Configuration\:
    resource: '*'
    exclude: 'Exception,Infrastructure'

  Ramsterhad\DeepDanbooruTagAssist\Framework\Configuration\Service\ConfigurationInterface:
    class: Ramsterhad\DeepDanbooruTagAssist\Framework\Configuration\Service\ConfigurationService
    public: true
