_default:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Frontpage\Controller\FrontpageController
  action: index

frontpage:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Frontpage\Controller\FrontpageController
  action: index

apiurlreset:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Frontpage\Controller\ApiUrlController
  action: resetApiUrlToDefault

apiurlset:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Frontpage\Controller\ApiUrlController
  action: setCustomApiUrl

pushnewtags:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Frontpage\Controller\PushTagsController
  action: pushNewTagsToDanbooru

auth:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Authentication\Controller\AuthenticationFormController
  action: index

authenticate:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Authentication\Controller\AuthenticationController
  action: checkAuthenticationRequest

logout:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Authentication\Controller\LogoutController
  action: index

