_default:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\FrontpageController
  action: index

frontpage:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\FrontpageController
  action: index

apiurlreset:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\ApiUrlController
  action: resetApiUrlToDefault

apiurlset:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\ApiUrlController
  action: setCustomApiUrl

pushnewtags:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Frontpage\PushTagsController
  action: pushNewTagsToDanbooru

auth:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\AuthenticationFormController
  action: index

authenticate:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\AuthenticationController
  action: checkAuthenticationRequest

logout:
  namespace: Ramsterhad\DeepDanbooruTagAssist\Application\Controller\Authentication\LogoutController
  action: index
