services:

  _defaults:
    public: false
    autowire: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\:
    resource: '*'
    exclude: 'templates'


  # Controller

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Authentication\AuthenticationController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Authentication\AuthenticationFormController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Authentication\LogoutController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Frontpage\ApiUrlController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Frontpage\FrontpageController:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Http\Controller\Frontpage\PushTagsController:
    public: true
